////
Copyright © 2016-2021 The Eclipse Foundation, Cirrus Link Solutions, and others

This program and the accompanying materials are made available under the
terms of the Eclipse Public License v. 2.0 which is available at
https://www.eclipse.org/legal/epl-2.0.

SPDX-License-Identifier: EPL-2.0

_Sparkplug™ and the Sparkplug™ logo are trademarks of the Eclipse Foundation_
////

[[conformance]]
== Conformance
// TODO: See Section 7 of http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html as a
// model to use for this chapter

[[conformance_profiles]]
=== Conformance Profiles

There are four Sparkplug target applications. A Sparkplug infrastructure typically consists of one
or more of the following application types

* Sparkplug Edge Node
* Sparkplug Primary Host Application
* Sparkplug Secondary Host Application
* MQTT Server

Each application type has specific conformance requirements that must be met. Typically a Sparkplug
application would only implement one of these profiles. For example an MQTT client wouldn't
typically be both an Edge Node and a Primary Host Application.

[[conformance_sparkplug_edge_node]]
==== Sparkplug Edge Node

A Sparkplug Edge Node is typically an 'Edge Gateway'. It sends and receives data to an MQTT Server
using the spBv1.0/# namespace. Edge Nodes typically interact with physical devices to gather data
and also write to device outputs.

[[conformance_sparkplug_primary_host_application]]
==== Sparkplug Primary Host Application

A Sparkplug Primary Host Application is typically at a 'central location' and primarily receives
data from multiple Sparkplug Edge Nodes. It also may send command messages to Sparkplug Edge Nodes
to write to outputs at Sparkplug devices. A Primary Host Application also sends rebirth requests to
Edge Nodes when required.
[tck-testable tck-id-conformance-primary-host]#[yellow-background]*Primary Host Application MUST
publish 'STATE' messages that represent its Birth and Death Certificates.*#

[[conformance_sparkplug_secondary_host_application]]
==== Sparkplug Secondary Host Application

A Sparkplug Secondary Host Application is typically at a 'central location' and primarily receives
data from multiple Sparkplug Edge Nodes. It also may send command messages to Sparkplug Edge Nodes
to write to outputs at Sparkplug devices. A Secondary Host Application also sends rebirth requests
to Edge Nodes when required.
[tck-testable tck-id-conformance-secondary-host]#[yellow-background]*Secondary Host Application MUST
NOT publish 'STATE' messages that represent its Birth and Death Certificates.*#

[[conformance_sparkplug_mqtt_server]]
==== Sparkplug MQTT Server

Sparkplug infrastructures have a specific subset of requirements on MQTT Servers. Any fully MQTT
v3.1.1 or v5.0 MQTT Server will meet the requirements of Sparkplug infrastructures. However, not all
of the features of the MQTT Specification are required. The following are the required portions of
the MQTT Specification.

* [tck-testable tck-id-conformance-mqtt-qos0]#[yellow-background]*A Sparkplug conformant MQTT Server
MUST support publish and subscribe on QoS 0*#
* [tck-testable tck-id-conformance-mqtt-qos1]#[yellow-background]*A Sparkplug conformant MQTT Server
MUST support publish and subscribe on QoS 1*#
* [tck-testable tck-id-conformance-mqtt-will-messages]#[yellow-background]*A Sparkplug conformant
MQTT Server MUST support all aspects of Will Messages including use of the 'retain flag' and QoS 1*#
* [tck-testable tck-id-conformance-mqtt-retained]#[yellow-background]*A Sparkplug conformant MQTT
Server MUST support all aspects of the 'retain flag'*#















