////
Copyright © 2016-2021 The Eclipse Foundation, Cirrus Link Solutions, and others

This program and the accompanying materials are made available under the
terms of the Eclipse Public License v. 2.0 which is available at
https://www.eclipse.org/legal/epl-2.0.

SPDX-License-Identifier: EPL-2.0

_Sparkplug™ and the Sparkplug™ logo are trademarks of the Eclipse Foundation_
////

[[security]]
== Security

[[security_tls]]
=== TLS
The MQTT specification does not specify any TCP/IP security scheme as it was envisaged that TCP/IP
security would (and did) change over time. Although this document will not specify any TCP/IP
security schema it will provide examples on how to secure an MQTT infrastructure using TLS security.

[[security_authentication]]
=== Authentication
There are several levels of security and access control configured within an MQTT infrastructure.
From a pure MQTT client perspective, the client does need to provide a unique Client ID, and an
optional username and password.

[[security_authorization]]
=== Authorization
Although access control is not mandated in the MQTT specification for use in MQTT Server
implementations, Access Control List (ACL) functionality is available for most MQTT Server
implementations. The ACL of an MQTT Server implementation is used to specify which Topic Namespace
any MQTT Client can subscribe to and publish on. Examples are provided on how to setup and manage
MQTT Client credentials and some considerations on setting up proper ACL’s on the MQTT Servers.

[[security_implementation_notes]]
=== Implementation Notes
