////
Copyright © 2016-2021 The Eclipse Foundation, Cirrus Link Solutions, and others

This program and the accompanying materials are made available under the
terms of the Eclipse Public License v. 2.0 which is available at
https://www.eclipse.org/legal/epl-2.0.

SPDX-License-Identifier: EPL-2.0

_Sparkplug™ and the Sparkplug™ logo are trademarks of the Eclipse Foundation_
////

[[topics]]
== Sparkplug™ Topic Namespace

To get a working Message Oriented Middleware based SCADA system using MQTT, the first thing that
must be defined is a topic namespace to work within. The beauty of MQTT is the fact that you can
just come up with an arbitrary topic like “Portland/Temperature”, connect to an MQTT Server, and
start publishing the temperature value. For this data to be useful to other MQTT Client applications
that want to consume the temperature values, the Topic Namespace needs to be understood by everyone
participating in the data exchange.

Every MQTT message published typically consists of a *_topic_* and *_payload_* components. These
components are the overhead of an MQTT message as measured in bytes on the wire. The Sparkplug
Specification is designed to keep these components meaningful and easy to understand, but not to get
so verbose as to negatively impact bandwidth/time sensitive data exchange.

[[topics_sparkplug_topic_namesapce_elements]]
=== Sparkplug Topic Namespace Elements

[tck-testable tck-id-topic-structure]#All MQTT clients using the Sparkplug specification MUST use
the following topic namespace structure:#

  namespace/group_id/message_type/edge_node_id/[device_id]

[[topics_namespace_element]]
==== namespace Element

The *_namespace_* element of the topic namespace is the root element that will define both the
structure of the remaining namespace elements as well as the encoding used for the associated
payload data. The Sparkplug specification defines two (2) namespaces. One is for Sparkplug payload
definition A, and another one of for the Sparkplug payload definition B.

[tck-testable tck-id-topic-structure-namespace-a]#For the Sparkplug A version of the payload
definition, the UTF-8 string constant for the *namespace* element MUST be:#

  spAv1.0

[tck-testable tck-id-topic-structure-namespace-a]#For the Sparkplug B version of the payload
definition, the UTF-8 string constant for the *_namespace_* element MUST be:#

  spBv1.0

Note that for the remainder of this document, the version of the Sparkplug Payload definition does
not affect the topic namespace or session state management as they will remain the same. There are
separate definitions in this document for the encoding used for both the A and B versions of
Sparkplug MQTT message payloads.

[[topics_group_id_element]]
==== group_id Element

The *_group_id_* element of the topic namespace provides for a logical grouping of Sparkplug Edge
Nodes into the MQTT Server and back out to the consuming MQTT Clients.
[tck-testable tck-id-topic-structure-namespace-valid-group-id]#The format of the  *_group_id_* MUST
be a valid UTF-8 string with the exception of the reserved characters of ‘+’ (plus), ‘/’ (forward
slash), and ‘#’ (number sign).#
In most use cases to minimize bandwidth, it should be descriptive but as small as possible. Examples
of where the [*group_id*] might be used include Oil/Gas applications where Sparkplug Edge Nodes on a
physical pipeline segment all have the same [*group_id*]. Plant floor applications may group
Sparkplug Edge Nodes based on logical cell or manufacturing line requirements.

[[topics_message_type_element]]
==== message_type Element

The *_message_type_* element of the topic namespace provides an indication as to how to handle the
MQTT payload of the message. Note that the actual encoding of the payload will vary depending on the
version of the Sparkplug implementation as indicated by the *_namespace_* element.

The following *_message_type_* elements are defined for the Sparkplug topic namespace:

* *NBIRTH* – Birth certificate for Sparkplug Edge Nodes
* *NDEATH* – Death certificate for Sparkplug Edge Nodes
* *DBIRTH* – Birth certificate for Devices
* *DDEATH* – Death certificate for Devices
* *NDATA* – Node data message
* *DDATA* – Device data message
* *NCMD* – Node command message
* *DCMD* – Device command message
* *STATE* – Primary Host application state message

The specification for each of these _message_type_ elements are detailed later in this document.

[[topics_edge_node_id_element]]
==== edge_node_id Element

The *_edge_node_id_* element of the Sparkplug topic namespace uniquely identifies the Sparkplug Edge
Node within the infrastructure.
[tck-testable tck-id-topic-structure-namespace-unique-edge-node-descriptor]#The *_group_id_*
combined with the *_edge_node_id_* element MUST be unique from any other
*_group_id_*/*_edge_node_id_* assigned in the MQTT infrastructure.#
[tck-testable tck-id-topic-structure-namespace-valid-edge-node-id]#The format of the
*_edge_node_id_* MUST be a valid UTF-8 string with the exception of the reserved characters of ‘+’
(plus), ‘/’ (forward slash), and ‘#’ (number sign).#
The topic element *_edge_node_id_* travels with every message published and should be as short as
 possible.

[[topics_device_id_element]]
==== device_id Element

The *_device_id_* element of the Sparkplug topic namespace identifies a device attached (physically
or logically) to the Sparkplug Edge Node. Note that the *_device_id_* is an optional element within
thetopic namespace as some messages will be either originating or destined to the *_edge_node_id_*
and the *_device_id_* would not be required.
[tck-testable tck-id-topic-structure-namespace-valid-device-id]#The format of the *_device_id_* MUST
be a valid UTF-8 string except for the reserved characters of ‘+’ (plus), ‘/’ (forward slash), and
‘#’ (number sign).#
[tck-testable tck-id-topic-structure-namespace-unique-device-id]#The *_device_id_* MUST be unique
from other devices connected to the same Edge Node.
[tck-testable tck-id-topic-structure-namespace-duplicate-device-id-across-eon]#The *_device_id_* MAY
be duplicated from Edge Node to other Edge Nodes. The device_id element travels with every message
published and should be as short as possible.
[tck-testable tck-id-topic-structure-namespace-device-id-associated-message-types]#The *_device_id_*
MUST be included with *_message_type_* elements DBIRTH, DDEATH, DDATA, and DCMD based topics#

[[topics_sparkplug_mqtt_message_types]]
=== Sparkplug MQTT Message Types

[[topics_message_type_oeverview]]
==== Message Type Overview

Sparkplug defines the topic namespace for set of MQTT messages that are used to manage connection
state as well as bidirectional metric information exchange that would apply to many typical
real-time SCADA/IIoT, monitoring, and data collection system use cases. The defined message types
are:

* *NBIRTH* – Birth certificate for Sparkplug Edge Nodes
* *NDEATH* – Death certificate for Sparkplug Edge Nodes
* *DBIRTH* – Birth certificate for Devices
* *DDEATH* – Death certificate for Devices
* *NDATA* – Node data message
* *DDATA* – Device data message
* *NCMD* – Node command message
* *DCMD* – Device command message
* *STATE* – Primary Host application state message

Using these defined messages host applications can:

* Discover all metadata and monitor state of all Edge Nodes and Devices connected to the MQTT
infrastructure.
* Discover all metrics which include all diagnostics, properties, metadata, and current state
values.
* Issue write/command messages to any Edge Node or Device metric.

This section of the document defines the topic namespace and how each of the associated messages
types can be used.

[[topics_edge_node]]
==== Edge Node
[upperalpha, start=1]

[[topics_birth_message_nbirth]]
===== Birth Message (NBIRTH)

The Birth Certificate topic for an Sparkplug Edge Node is:
[subs="quotes"]
  namespace/group_id/*NBIRTH*/edge_node_id

The Sparkplug Edge Node Birth Certificate payload contains everything required to build out a data
structure for all metrics for this Edge Node. At the time any host application receives and NBIRTH,
the ONLINE state of this Edge Node should be set to TRUE along with the associated ONLINE Date Time
parameter. Note that the Edge Node Birth Certificate ONLY indicates the node itself is online and in
an MQTT Session, but any devices that have previously published a DBIRTH will still have “*STALE*”
metric quality until the host application receives the associated DBIRTH messages.

[[topics_data_message_ndata]]
===== Data Message (NDATA)

Once an Sparkplug Edge Node is online with a proper NBIRTH it is in a mode of quiescent Report by
Exception (RBE) or time based reporting of metric information that changes. This enables the
advantages of the native Continuous Session Awareness of MQTT to monitor the STATE of all connected
Sparkplug Edge Node and to rely on Report by Exception (RBE) messages for metric state changes over
the MQTT session connection. The Data Topic for an Sparkplug Edge Node is:
[subs="quotes"]
  namespace/group_id/*NDATA*/edge_node_id

The payload of NDATA messages will contain any RBE or time based metric Edge Node values that need
to be reported to any subscribing MQTT clients.

[[topics_death_message_ndeath]]
===== Death Message (NDEATH)

The Death Certificate topic for an Sparkplug Edge Node is:
[subs="quotes"]
  namespace/group_id/*NDEATH*/edge_node_id

The Death Certificate topic and payload described here are not “published” as an MQTT message by a
client, but provided as parameters within the MQTT CONNECT control packet when this Sparkplug Edge
Node first establishes the MQTT Client session.

Immediately upon reception of an Edge Node Death Certificate, any MQTT client subscribed to this
Edge Node should set the data quality of all metrics to STALE and should note the time stamp when
the NDEATH message was received.

The MQTT payload typically associated with this topic can include a Birth/Death sequence number used
to track and synchronize Birth and Death sequences across the MQTT infrastructure. Since this
payload will be defined in advance, and held in the MQTT server and only delivered on the
termination of an MQTT session, not a lot of additional diagnostic information can be pre-populated
into the payload.

[[topics_command_ncmd]]
===== Command (NCMD)

The NCMD command topic provides the topic namespace used to send commands to any connected Edge
Nodes. This means sending an updated metric value to an associated metric included in the NBIRTH
metric list.
[subs="quotes"]
  namespace/group_id/*NCMD*/edge_node_id

[[topics_device_sensor]]  
==== Device / Sensor
[upperalpha, start=1]

[[topics_birth_message_dbirth]]
===== Birth Message (DBIRTH)

The topic namespace for a Birth Certificate for a device is:
[subs="quotes"]
  namespace/group_id/*DBIRTH*/edge_node_id/device_id

The DBIRTH payload contains everything required to build out a data structure for all metrics for
this device. The ONLINE state of this device should be set to TRUE along with the associated ONLINE
date time this message was received.

The Sparkplug Edge Node is responsible for the management of all attached physical and/or logical
devices. Once the Edge Node has published its NBIRTH, any consumer application ensures that the
metric structure has the Edge Node in an ONLINE state. But each physical and/or logical device
connected to this node will still need to provide this DBIRTH before consumer applications
create/update the metric structure (if this is the first time this device has been seen) and set any
associated metrics in the application to a “*GOOD*” state.

[[topics_data_message_ddata]]
===== Data Message (DDATA)

Once an Sparkplug Edge Node and associated devices are all online with proper Birth Certificates it
is in a mode of quiescent Report by Exception (RBE) reporting of any metric that changes. This takes
advantage of the native Continuous Session Awareness of MQTT to monitor the STATE of all connected
devices and can rely on Report by Exception (RBE) messages for any metric value change over the MQTT
session connection.

As defined above, the Data Topic for an MQTT device is:
[subs="quotes"]
  namespace/group_id/*DDATA*/edge_node_id/device_id

The payload of DDATA messages can contain one or more metric values that need to be reported.

[[topics_death_message_ddeath]]
===== Death Message (DDEATH)

The Sparkplug topic namespace for a device Death Certificate is:
[subs="quotes"]
  namespace/group_id/*DDEATH*/edge_node_id/device_id

It is the responsibility of the Sparkplug Edge Node to indicate the real-time state of either
physical legacy device using poll/response protocols and/or local logical devices. If the device
becomes unavailable for any reason (no response, CRC error, etc.) it is the responsibility of the
Edge Node to publish a DDEATH on behalf of the end device.

Immediately upon reception of a DDEATH, any MQTT client subscribed to this device should set the
data quality of all metrics to “*STALE”* and should note the time stamp when the DDEATH message was
received.

[[topics_command_dcmd]]
===== Command (DCMD)

The DCMD topic provides the topic namespace used to publish metrics to any connected device. This
means sending a new metric value to an associated metric included in the DBIRTH metric list.
[subs="quotes"]
  namespace/group_id/*DCMD*/edge_node_id/device_id

[[topics_scada_iiot_host]]
==== SCADA / IIoT Host
[upperalpha, start=1]

[[topics_birth_message_state]]
===== Birth Message (STATE)

[tck-testable tck-id-host-topic-phid-birth-payload]#The first message a Primary Host Application
MUST publish is a Birth Certificate.#
The Primary Host Application Death Certificate is registered above within the actual establishment
of the MQTT session and is published as a part of the native MQTT transport if the MQTT session
terminates for any reason.

The Birth Certificate that is defined here is an application level message published by the Primary
Host Application MQTT Client applications.

The topic used for the Host Birth Certificate is identical to the topic used for the Death
Certificate:
[subs="quotes"]
  *STATE*/scada_host_id

[tck-testable tck-id-host-topic-phid-birth-payload]#The Birth Certificate Payload MUST be the UTF-8
string “*ONLINE*”.#

[tck-testable tck-id-host-topic-phid-birth-qos]#The MQTT Quality of Service (QoS) MUST be set to
*1*.#

[tck-testable tck-id-host-topic-phid-birth-retain]#The MQTT retain flag for the Birth Certificate
MUST be set to *TRUE*#

[[topics_death_message_state]]
===== Death Message (STATE)

When the SCADA/IIoT Host MQTT client establishes an MQTT session to the MQTT Server(s), the Death
Certificate will be part of the Will Topic and Will Payload registered in the MQTT CONNECT
transaction. The *Will Topic* as defined above will be:
[subs="quotes"]
  *STATE*/scada_host_id

[tck-testable tck-id-host-topic-phid-death-payload]#The MQTT Will Payload MUST be the UTF-8 string
“*OFFLINE*”.#

[tck-testable tck-id-host-topic-phid-death-qos]#The MQTT Will QoS MUST be set to *1*#

[tck-testable tck-id-host-topic-phid-death-retain]#The MQTT Will retain flag MUST be set to *TRUE*#

