@startuml
participant "Primary Application" as PrimApp #lightblue
database "MQTT Server" as Server #lightblue
participant "MQTT EoN Node" as EoN #lightblue

activate PrimApp
activate Server
activate EoN


autonumber 1 "<b>(#)"
PrimApp <--> Server
autonumber 1 "<b>(#)"
Server <--> EoN

PrimApp <--> Server


Server <--> EoN
autonumber 3 "<b>(#)"
PrimApp <--> EoN
note left
All metrics provided in Birth
Certificate are created in the
EoN Node folder within the
Primary Application
end note

|||

Server <- EoN : PUBLISH( **NDATA** )
note right
Cellular RSSI level changes
value. New value is updated
in a payload and published.
end note

autonumber 4 "<b>(#)"
PrimApp <-- Server
note left
New RSSI metric is updated in
the associated EoN Node
folder.
end note

|||

autonumber 5 "<b>(#)"
PrimApp -> Server : PUBLISH( **NCMD** )
note left
Send a command to the EoN
Node to set Ethernet as the
Primary network. Writing to
the tag PRI_NETWORK in
the Primary Application will
automatically publish the
new value.
end note

autonumber 5 "<b>(#)"
Server --> EoN
note right
PRI_NETWORK set to a
new value of 2.
end note

|||
@enduml