@startuml
participant "Primary Application" as PrimApp #lightblue
database "MQTT Server" as Server #lightblue
participant "MQTT EoN Node" as EoN #lightblue

activate PrimApp
activate Server


autonumber 1 "<b>(#)"
Server <- EoN : CONNECT

|||

Server <- EoN : PUBLISH( **NBIRTH** )
activate EoN

note left
Create/update Eon Node
folder and metrics.
Create and update all
metrics and set data
quality to 'GOOD'.
end note

Server <- EoN : SUBSCRIBE( **NCMD, DCMD, STATE** )

note right of EoN
MQTT EoN Node Session
established. Current 'STATE'
is ONLINE.
end note

... (normal operation) ...
|||

Server <--> EoN : "Loss of Connection"
autonumber stop
deactivate EoN

[<-- Server : Death Certificate

note left of Server
All EoN Node metrics set
to 'STALE'. OFFLINE
time and metrics updated.
end note

note right of EoN
MQTT EoN Node
Session terminated.
Current 'STATE' is
OFFLINE.
end note

|||

Server <- EoN : CONNECT

|||
Server <- EoN : PUBLISH( **NBIRTH** )
activate EoN
note left
All EoN Node metrics set
to 'GOOD'. OFFLINE
time and metrics updated.
end note


Server <- EoN : SUBSCRIBE( **NCMD, DCMD, STATE** )

note right of EoN
MQTT EoN Node Session
reestablished. Current 'STATE'
is ONLINE.
end note

|||
@enduml